### ISSUE TITLE
Make sure SSL is enabled on Pantheon

### ISSUE THREAD

**Issue by sofiakanopi** [kanopi/wp-launch-checklist#11]
On Threshold Choir, the `pantheon.yml` was incomplete. It was missing the following value to make sure Dev and Test have SSL enabled:

`enforce_https: full+subdomains`

It would be great to review this from now on.

**Comment by damonsharp** [comment]
Addressed in [this PR](https://github.com/kanopi/wp-launch-checklist/pull/12). Assigned to you Sofia for a review.
